### PR TITLE
serr

### PR DESCRIPTION
**Pull request by phomola**

### CODE REVIEW

**Comment by OndrejBelza** [comment]
Should this me separate repo? @phomola

**Comment by phomola** [comment]
> Should this me separate repo? @phomola

I don't think so, it's a separate package.

**Comment by OndrejBelza** [comment]
> > Should this me separate repo? @phomola
> 
> I don't think so, it's a separate package.

But if it's part of golibs, then you are carrying all dependencies from other libs. Currently we have only pointer lib here, but if future we could have more libs here. Benefit of separating serr to new repo would also be, that if you only use serr (mostly stable lib without lot of changes), renovate would not be triggered that often.

**Review by OndrejBelza — APPROVED** [review]

**Review by sitavanc — APPROVED** [review]

**Comment by phomola** [comment]
> > > Should this me separate repo? @phomola
> > 
> > 
> > I don't think so, it's a separate package.
> 
> But if it's part of golibs, then you are carrying all dependencies from other libs. Currently we have only pointer lib here, but if future we could have more libs here. Benefit of separating serr to new repo would also be, that if you only use serr (mostly stable lib without lot of changes), renovate would not be triggered that often.

I think this has been resolved at the standup, right?

**Pull request merged**
